// Datenbank mit deutschen Kennzeichenpräfixen und zugehörigen Städten
const licensePlatePrefixes: Record<string, { city: string; message: string; emoji: string }> = {
  // A
  A: { city: "Augsburg", message: "Schöne Stadt in Bayern!", emoji: "🏰" },
  AA: { city: "Ostalbkreis", message: "Wunderschöne Landschaft!", emoji: "🌄" },
  AB: { city: "Aschaffenburg", message: "Tor zum Spessart!", emoji: "🌳" },
  ABG: { city: "Altenburger Land", message: "Heimat des Skatspiels!", emoji: "🃏" },
  ABI: { city: "Anhalt-Bitterfeld", message: "Willkommen in Sachsen-Anhalt!", emoji: "🏞️" },
  AC: { city: "Aachen", message: "Stadt Karls des Großen!", emoji: "👑" },
  AIC: { city: "Aichach-Friedberg", message: "Herzlich willkommen in Schwaben!", emoji: "💙" },
  AK: { city: "Altenkirchen", message: "Schönes Westerwald!", emoji: "🌲" },
  AM: { city: "Amberg", message: "Willkommen in der Oberpfalz!", emoji: "🏙️" },
  AN: { city: "Ansbach", message: "Residenzstadt in Franken!", emoji: "🏛️" },
  ANA: { city: "Annaberg", message: "Schönes Erzgebirge!", emoji: "⛰️" },
  AÖ: { city: "Altötting", message: "Bekannter Wallfahrtsort!", emoji: "⛪" },
  AP: { city: "Weimarer Land", message: "Kulturregion Thüringen!", emoji: "📚" },
  APD: { city: "Weimarer Land", message: "Heimat großer Dichter!", emoji: "✍️" },
  AS: { city: "Amberg-Sulzbach", message: "Herzlich willkommen in der Oberpfalz!", emoji: "🏞️" },
  ASL: { city: "Aschersleben-Staßfurt", message: "Willkommen in Sachsen-Anhalt!", emoji: "🏘️" },
  AT: { city: "Altentreptow", message: "Schöne Landschaft in MV!", emoji: "🌊" },
  AU: { city: "Aue", message: "Willkommen im Erzgebirge!", emoji: "⛏️" },
  AUR: { city: "Aurich", message: "Schönes Ostfriesland!", emoji: "🌊" },
  AW: { city: "Ahrweiler", message: "Bekannt für guten Wein!", emoji: "🍷" },
  AZ: { city: "Alzey", message: "Tor zur Rheinhessischen Schweiz!", emoji: "🍇" },

  // B
  B: { city: "Berlin", message: "Hauptstadt mit Herz!", emoji: "🐻" },
  BA: { city: "Bamberg", message: "UNESCO-Weltkulturerbe!", emoji: "🏛️" },
  BAD: { city: "Baden-Baden", message: "Elegante Kurstadt!", emoji: "♨️" },
  BAR: { city: "Barnim", message: "Schönes Brandenburg!", emoji: "🌳" },
  BB: { city: "Böblingen", message: "Hightech im Grünen!", emoji: "💻" },
  BBL: { city: "Brandenburg", message: "Stadt an der Havel!", emoji: "🚣" },
  BC: { city: "Biberach", message: "Schönes Oberschwaben!", emoji: "🏞️" },
  BCH: { city: "Buchen", message: "Tor zum Odenwald!", emoji: "🌳" },
  BE: { city: "Beckum", message: "Schönes Münsterland!", emoji: "🏰" },
  BED: { city: "Brand-Erbisdorf", message: "Willkommen im Erzgebirge!", emoji: "⛏️" },
  BER: { city: "Bernau", message: "Vor den Toren Berlins!", emoji: "🏙️" },
  BF: { city: "Steinfurt", message: "Schönes Münsterland!", emoji: "🏰" },
  BGL: { city: "Berchtesgadener Land", message: "Traumhafte Alpenlandschaft!", emoji: "🏔️" },
  BI: { city: "Bielefeld", message: "Existiert wirklich! 😉", emoji: "🦄" },
  BIR: { city: "Birkenfeld", message: "Schöner Naturpark!", emoji: "🌲" },
  BIT: { city: "Bitburg", message: "Bekannt für gutes Bier!", emoji: "🍺" },
  BK: { city: "Bördekreis", message: "Fruchtbare Region!", emoji: "🌾" },
  BL: { city: "Zollernalbkreis", message: "Schöne Schwäbische Alb!", emoji: "⛰️" },
  BLB: { city: "Bad Berleburg", message: "Schönes Wittgenstein!", emoji: "🏞️" },
  BLK: { city: "Burgenlandkreis", message: "Willkommen in Sachsen-Anhalt!", emoji: "🏰" },
  BM: { city: "Bergheim", message: "Willkommen im Rheinland!", emoji: "🏞️" },
  BN: { city: "Bonn", message: "Ehemalige Bundeshauptstadt!", emoji: "🏛️" },
  BO: { city: "Bochum", message: "Herz des Ruhrgebiets!", emoji: "⚒️" },
  BÖ: { city: "Börde", message: "Fruchtbare Region!", emoji: "🌾" },
  BOH: { city: "Borna", message: "Willkommen in Sachsen!", emoji: "⛏️" },
  BOR: { city: "Borken", message: "Schönes Münsterland!", emoji: "🏰" },
  BOT: { city: "Bottrop", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  BP: { city: "Bundespolizei", message: "Sicherheit für Deutschland!", emoji: "👮" },
  BRA: { city: "Brake", message: "Schönes Wesermarsch!", emoji: "🚢" },
  BRB: { city: "Brandenburg", message: "Stadt an der Havel!", emoji: "🚣" },
  BS: { city: "Braunschweig", message: "Löwenstadt!", emoji: "🦁" },
  BT: { city: "Bayreuth", message: "Stadt der Wagner-Festspiele!", emoji: "🎭" },
  BTF: { city: "Bitterfeld", message: "Industriestadt mit Herz!", emoji: "🏭" },
  BÜD: { city: "Büdingen", message: "Mittelalterliche Stadt!", emoji: "🏰" },
  BÜS: { city: "Büsingen", message: "Deutsche Exklave in der Schweiz!", emoji: "🇨🇭" },
  BÜZ: { city: "Bützow", message: "Schönes Mecklenburg!", emoji: "🏞️" },
  BW: { city: "Bundes-Wasser-Schutzpolizei", message: "Sicherheit auf dem Wasser!", emoji: "🚤" },
  BWL: { city: "Bundeswehr Liegenschaften", message: "Für die Verteidigung!", emoji: "🪖" },
  BYL: { city: "Bayreuth-Land", message: "Schönes Oberfranken!", emoji: "🏞️" },

  // C
  C: { city: "Chemnitz", message: "Stadt der Moderne!", emoji: "🏙️" },
  CA: { city: "Calau", message: "Bekannt für seine Witze!", emoji: "😄" },
  CAS: { city: "Castrop-Rauxel", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  CB: { city: "Cottbus", message: "Tor zum Spreewald!", emoji: "🛶" },
  CE: { city: "Celle", message: "Stadt mit Fachwerkhäusern!", emoji: "🏠" },
  CHA: { city: "Cham", message: "Tor zum Bayerischen Wald!", emoji: "🌲" },
  CLP: { city: "Cloppenburg", message: "Schönes Oldenburger Münsterland!", emoji: "🐄" },
  CO: { city: "Coburg", message: "Stadt der Veste!", emoji: "🏰" },
  COC: { city: "Cochem-Zell", message: "Romantische Moselregion!", emoji: "🍇" },
  COE: { city: "Coesfeld", message: "Schönes Münsterland!", emoji: "🏰" },
  CR: { city: "Crailsheim", message: "Stadt an der Jagst!", emoji: "🏞️" },
  CUX: { city: "Cuxhaven", message: "Stadt an der Nordsee!", emoji: "⚓" },
  CW: { city: "Calw", message: "Heimat von Hermann Hesse!", emoji: "📚" },

  // D
  D: { city: "Düsseldorf", message: "Schicke Landeshauptstadt!", emoji: "🛍️" },
  DA: { city: "Darmstadt", message: "Wissenschaftsstadt!", emoji: "🔬" },
  DAH: { city: "Dachau", message: "Stadt mit Geschichte!", emoji: "🏛️" },
  DAN: { city: "Lüchow-Dannenberg", message: "Schönes Wendland!", emoji: "🌳" },
  DAU: { city: "Daun", message: "Vulkaneifel pur!", emoji: "🌋" },
  DB: { city: "Deutsche Bahn", message: "Mobilität für Deutschland!", emoji: "🚆" },
  DBR: { city: "Bad Doberan", message: "Schöne Ostseeregion!", emoji: "🌊" },
  DD: { city: "Dresden", message: "Florenz an der Elbe!", emoji: "🏛️" },
  DE: { city: "Dessau-Roßlau", message: "Stadt des Bauhauses!", emoji: "🏛️" },
  DEG: { city: "Deggendorf", message: "Tor zum Bayerischen Wald!", emoji: "🌲" },
  DEL: { city: "Delmenhorst", message: "Stadt an der Delme!", emoji: "🏙️" },
  DGF: { city: "Dingolfing-Landau", message: "Automobilstandort in Niederbayern!", emoji: "🚗" },
  DH: { city: "Diepholz", message: "Schönes Niedersachsen!", emoji: "🏞️" },
  DI: { city: "Dillkreis", message: "Schönes Hessen!", emoji: "🏞️" },
  DIL: { city: "Lahn-Dill-Kreis", message: "Mittelhessen pur!", emoji: "🏞️" },
  DIN: { city: "Dinslaken", message: "Stadt am Niederrhein!", emoji: "🏞️" },
  DIZ: { city: "Diez", message: "Stadt an der Lahn!", emoji: "🏞️" },
  DKB: { city: "Dinkelsbühl", message: "Mittelalterliche Stadt!", emoji: "🏰" },
  DL: { city: "Döbeln", message: "Stadt in Sachsen!", emoji: "🏙️" },
  DLG: { city: "Dillingen an der Donau", message: "Universitätsstadt in Schwaben!", emoji: "🎓" },
  DM: { city: "Demmin", message: "Stadt in Vorpommern!", emoji: "🏞️" },
  DN: { city: "Düren", message: "Stadt an der Rur!", emoji: "🏞️" },
  DO: { city: "Dortmund", message: "Fußballstadt im Ruhrgebiet!", emoji: "⚽" },
  DON: { city: "Donau-Ries", message: "Schönes Schwaben!", emoji: "🏞️" },
  DU: { city: "Duisburg", message: "Stadt der Häfen!", emoji: "🚢" },
  DÜW: { city: "Bad Dürkheim", message: "Bekannt für die Wurstmarkt!", emoji: "🍷" },
  DW: { city: "Dippoldiswalde", message: "Tor zum Osterzgebirge!", emoji: "⛰️" },
  DZ: { city: "Delitzsch", message: "Stadt in Sachsen!", emoji: "🏙️" },

  // E
  E: { city: "Essen", message: "Kulturhauptstadt im Ruhrgebiet!", emoji: "🏙️" },
  EA: { city: "Eisenach", message: "Stadt der Wartburg!", emoji: "🏰" },
  EB: { city: "Eilenburg", message: "Stadt in Sachsen!", emoji: "🏙️" },
  EBE: { city: "Ebersberg", message: "Schönes Oberbayern!", emoji: "🏞️" },
  EBS: { city: "Ebermannstadt", message: "Tor zur Fränkischen Schweiz!", emoji: "⛰️" },
  ECK: { city: "Eckernförde", message: "Schöne Ostseestadt!", emoji: "🌊" },
  ED: { city: "Erding", message: "Bekannt für Weißbier!", emoji: "🍺" },
  EE: { city: "Elbe-Elster", message: "Schönes Brandenburg!", emoji: "🏞️" },
  EF: { city: "Erfurt", message: "Landeshauptstadt Thüringens!", emoji: "🏛️" },
  EG: { city: "Eggenfelden", message: "Stadt in Niederbayern!", emoji: "🏙️" },
  EH: { city: "Eisenhüttenstadt", message: "Stadt an der Oder!", emoji: "🏙️" },
  EI: { city: "Eichstätt", message: "Universitätsstadt in Bayern!", emoji: "🎓" },
  EIC: { city: "Eichsfeld", message: "Schönes Thüringen!", emoji: "🏞️" },
  EIL: { city: "Eisleben", message: "Lutherstadt!", emoji: "⛪" },
  EIN: { city: "Einbeck", message: "Bekannt für Bier!", emoji: "🍺" },
  EIS: { city: "Eisenberg", message: "Stadt in Thüringen!", emoji: "🏙️" },
  EL: { city: "Emsland", message: "Schönes Niedersachsen!", emoji: "🏞️" },
  EM: { city: "Emmendingen", message: "Schönes Baden!", emoji: "🏞️" },
  EMD: { city: "Emden", message: "Hafenstadt in Ostfriesland!", emoji: "⚓" },
  EMS: { city: "Bad Ems", message: "Bekannter Kurort!", emoji: "♨️" },
  EN: { city: "Ennepe-Ruhr-Kreis", message: "Schönes Ruhrgebiet!", emoji: "🏞️" },
  ER: { city: "Erlangen", message: "Universitätsstadt in Franken!", emoji: "🎓" },
  ERB: { city: "Odenwaldkreis", message: "Schöner Odenwald!", emoji: "🌳" },
  ERH: { city: "Erlangen-Höchstadt", message: "Schönes Franken!", emoji: "🏞️" },
  ERK: { city: "Erkelenz", message: "Stadt am Niederrhein!", emoji: "🏙️" },
  ERZ: { city: "Erzgebirgskreis", message: "Schönes Erzgebirge!", emoji: "⛰️" },
  ES: { city: "Esslingen", message: "Stadt am Neckar!", emoji: "🏞️" },
  ESB: { city: "Eschenbach in der Oberpfalz", message: "Schöne Oberpfalz!", emoji: "🏞️" },
  ESW: { city: "Werra-Meißner-Kreis", message: "Schönes Nordhessen!", emoji: "🏞️" },
  EU: { city: "Euskirchen", message: "Stadt in der Eifel!", emoji: "🏞️" },
  EW: { city: "Eberswalde", message: "Stadt im Barnim!", emoji: "🌳" },

  // F
  F: { city: "Frankfurt am Main", message: "Bankenmetropole mit Herz!", emoji: "🏙️" },
  FB: { city: "Wetteraukreis", message: "Schöne Wetterau!", emoji: "🏞️" },
  FD: { city: "Fulda", message: "Barockstadt in Hessen!", emoji: "🏛️" },
  FDB: { city: "Friedberg", message: "Stadt in der Wetterau!", emoji: "🏙️" },
  FDS: { city: "Freudenstadt", message: "Kurstadt im Schwarzwald!", emoji: "🌲" },
  FEU: { city: "Feuchtwangen", message: "Stadt in Mittelfranken!", emoji: "🏙️" },
  FF: { city: "Frankfurt (Oder)", message: "Stadt an der Oder!", emoji: "🏙️" },
  FFB: { city: "Fürstenfeldbruck", message: "Schönes Oberbayern!", emoji: "🏞️" },
  FG: { city: "Freiberg", message: "Universitätsstadt in Sachsen!", emoji: "🎓" },
  FI: { city: "Finsterwalde", message: "Sängerstadt in Brandenburg!", emoji: "🎵" },
  FKB: { city: "Frankenberg", message: "Stadt in Sachsen!", emoji: "🏙️" },
  FL: { city: "Flensburg", message: "Stadt an der Förde!", emoji: "⚓" },
  FLÖ: { city: "Flöha", message: "Stadt in Sachsen!", emoji: "🏙️" },
  FN: { city: "Friedrichshafen", message: "Stadt am Bodensee!", emoji: "🚤" },
  FO: { city: "Forchheim", message: "Tor zur Fränkischen Schweiz!", emoji: "⛰️" },
  FOR: { city: "Forst", message: "Rosenstadt in der Lausitz!", emoji: "🌹" },
  FR: { city: "Freiburg", message: "Sonnigste Stadt Deutschlands!", emoji: "☀️" },
  FRG: { city: "Freyung-Grafenau", message: "Schöner Bayerischer Wald!", emoji: "🌲" },
  FRI: { city: "Friesland", message: "Schönes Ostfriesland!", emoji: "🌊" },
  FRW: { city: "Bad Freienwalde", message: "Ältestes Heilbad Brandenburgs!", emoji: "♨️" },
  FS: { city: "Freising", message: "Domstadt an der Isar!", emoji: "⛪" },
  FT: { city: "Frankenthal", message: "Stadt in der Pfalz!", emoji: "🏙️" },
  FTL: { city: "Freital", message: "Stadt in Sachsen!", emoji: "🏙️" },
  FÜ: { city: "Fürth", message: "Kleeblattstadt in Franken!", emoji: "☘️" },
  FÜS: { city: "Füssen", message: "Stadt am Fuße der Alpen!", emoji: "🏔️" },
  FW: { city: "Fürstenwalde", message: "Stadt an der Spree!", emoji: "🏙️" },
  FZ: { city: "Fritzlar", message: "Domstadt in Nordhessen!", emoji: "⛪" },

  // G
  G: { city: "Gera", message: "Stadt in Thüringen!", emoji: "🏙️" },
  GA: { city: "Gardelegen", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  GAN: { city: "Bad Gandersheim", message: "Kurstadt in Niedersachsen!", emoji: "♨️" },
  GAP: { city: "Garmisch-Partenkirchen", message: "Traumhafte Alpenlandschaft!", emoji: "🏔️" },
  GC: { city: "Chemnitz", message: "Stadt der Moderne!", emoji: "🏙️" },
  GD: { city: "Schwäbisch Gmünd", message: "Stauferstadt in Württemberg!", emoji: "🏰" },
  GDB: { city: "Gadebusch", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  GE: { city: "Gelsenkirchen", message: "Stadt der tausend Feuer!", emoji: "⚒️" },
  GEL: { city: "Geldern", message: "Stadt am Niederrhein!", emoji: "🏙️" },
  GEO: { city: "Gerolzhofen", message: "Stadt in Unterfranken!", emoji: "🏙️" },
  GER: { city: "Germersheim", message: "Festungsstadt am Rhein!", emoji: "🏰" },
  GF: { city: "Gifhorn", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  GG: { city: "Groß-Gerau", message: "Stadt in Hessen!", emoji: "🏙️" },
  GHA: { city: "Geithain", message: "Stadt in Sachsen!", emoji: "🏙️" },
  GHC: { city: "Gräfenhainichen", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  GI: { city: "Gießen", message: "Universitätsstadt in Hessen!", emoji: "🎓" },
  GK: { city: "Geilenkirchen", message: "Stadt in Nordrhein-Westfalen!", emoji: "🏙️" },
  GL: { city: "Bergisch Gladbach", message: "Stadt im Bergischen Land!", emoji: "⛰️" },
  GLA: { city: "Gladbeck", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  GM: { city: "Grimma", message: "Stadt in Sachsen!", emoji: "🏙️" },
  GMN: { city: "Grimmen", message: "Stadt in Vorpommern!", emoji: "🏙️" },
  GNT: { city: "Genthin", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  GÖ: { city: "Göttingen", message: "Universitätsstadt in Niedersachsen!", emoji: "🎓" },
  GOA: { city: "Sankt Goar", message: "Stadt am Rhein!", emoji: "🏞️" },
  GOH: { city: "Gotha", message: "Residenzstadt in Thüringen!", emoji: "🏰" },
  GP: { city: "Göppingen", message: "Stadt in Baden-Württemberg!", emoji: "🏙️" },
  GR: { city: "Greiz", message: "Perle des Vogtlandes!", emoji: "🏞️" },
  GRA: { city: "Grafenau", message: "Stadt im Bayerischen Wald!", emoji: "🌲" },
  GRH: { city: "Großenhain", message: "Stadt in Sachsen!", emoji: "🏙️" },
  GRI: { city: "Griesbach im Rottal", message: "Stadt in Niederbayern!", emoji: "🏙️" },
  GRM: { city: "Grimmen", message: "Stadt in Vorpommern!", emoji: "🏙️" },
  GRZ: { city: "Greiz", message: "Perle des Vogtlandes!", emoji: "🏞️" },
  GS: { city: "Goslar", message: "UNESCO-Weltkulturerbe im Harz!", emoji: "⛰️" },
  GT: { city: "Gütersloh", message: "Stadt in Ostwestfalen!", emoji: "🏙️" },
  GTH: { city: "Gotha", message: "Residenzstadt in Thüringen!", emoji: "🏰" },
  GÜ: { city: "Güstrow", message: "Barlachstadt in Mecklenburg!", emoji: "🎨" },
  GUB: { city: "Guben", message: "Stadt an der Neiße!", emoji: "🏙️" },
  GVM: { city: "Grevesmühlen", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  GW: { city: "Greifswald", message: "Universitätsstadt an der Ostsee!", emoji: "🎓" },
  GZ: { city: "Günzburg", message: "Stadt in Schwaben!", emoji: "🏙️" },

  // H
  H: { city: "Hannover", message: "Landeshauptstadt Niedersachsens!", emoji: "🏛️" },
  HA: { city: "Hagen", message: "Stadt am Rande des Ruhrgebiets!", emoji: "🏙️" },
  HAB: { city: "Hammelburg", message: "Weinstadt in Franken!", emoji: "🍇" },
  HAL: { city: "Halle (Saale)", message: "Stadt der Händel-Festspiele!", emoji: "🎵" },
  HAM: { city: "Hamm", message: "Stadt in Westfalen!", emoji: "🏙️" },
  HAS: { city: "Haßberge", message: "Schönes Unterfranken!", emoji: "🏞️" },
  HB: { city: "Bremen", message: "Hansestadt an der Weser!", emoji: "⚓" },
  HBN: { city: "Hildburghausen", message: "Stadt in Thüringen!", emoji: "🏙️" },
  HC: { city: "Hechingen", message: "Stadt in Baden-Württemberg!", emoji: "🏙️" },
  HD: { city: "Heidelberg", message: "Romantische Stadt am Neckar!", emoji: "🏰" },
  HDH: { city: "Heidenheim", message: "Stadt auf der Ostalb!", emoji: "🏙️" },
  HDL: { city: "Haldensleben", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  HE: { city: "Helmstedt", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  HEB: { city: "Hersbruck", message: "Stadt in Mittelfranken!", emoji: "🏙️" },
  HEF: { city: "Hersfeld-Rotenburg", message: "Schönes Nordhessen!", emoji: "🏞️" },
  HEI: { city: "Heide", message: "Stadt in Dithmarschen!", emoji: "🏙️" },
  HER: { city: "Herne", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  HET: { city: "Hettstedt", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  HF: { city: "Herford", message: "Stadt in Ostwestfalen!", emoji: "🏙️" },
  HG: { city: "Bad Homburg", message: "Kurstadt im Taunus!", emoji: "♨️" },
  HGN: { city: "Hagenow", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  HGW: { city: "Greifswald", message: "Universitätsstadt an der Ostsee!", emoji: "🎓" },
  HH: { city: "Hamburg", message: "Schöne Stadt an der Elbe!", emoji: "⚓" },
  HHM: { city: "Hohenmoelsen", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  HI: { city: "Hildesheim", message: "Stadt der Weltkulturerbe!", emoji: "🏛️" },
  HIG: { city: "Heiligenstadt", message: "Stadt im Eichsfeld!", emoji: "🏙️" },
  HIP: { city: "Hilpoltstein", message: "Stadt in Mittelfranken!", emoji: "🏙️" },
  HK: { city: "Heidekreis", message: "Schöne Lüneburger Heide!", emoji: "🌾" },
  HL: { city: "Lübeck", message: "Hansestadt an der Ostsee!", emoji: "⚓" },
  HM: { city: "Hameln", message: "Stadt des Rattenfängers!", emoji: "🎵" },
  HMÜ: { city: "Hannoversch Münden", message: "Stadt an drei Flüssen!", emoji: "🏞️" },
  HN: { city: "Heilbronn", message: "Stadt am Neckar!", emoji: "🏞️" },
  HO: { city: "Hof", message: "Stadt in Oberfranken!", emoji: "🏙️" },
  HOG: { city: "Hofgeismar", message: "Stadt in Nordhessen!", emoji: "🏙️" },
  HOH: { city: "Hofheim", message: "Stadt im Taunus!", emoji: "⛰️" },
  HOL: { city: "Holzminden", message: "Stadt an der Weser!", emoji: "🏞️" },
  HOM: { city: "Homburg", message: "Stadt im Saarland!", emoji: "🏙️" },
  HOR: { city: "Horb", message: "Stadt am Neckar!", emoji: "🏞️" },
  HOT: { city: "Hohenstein-Ernstthal", message: "Stadt in Sachsen!", emoji: "🏙️" },
  HP: { city: "Bergstraße", message: "Schöne Bergstraße!", emoji: "🏞️" },
  HR: { city: "Schwalm-Eder-Kreis", message: "Schönes Nordhessen!", emoji: "🏞️" },
  HRO: { city: "Rostock", message: "Hansestadt an der Ostsee!", emoji: "⚓" },
  HS: { city: "Heinsberg", message: "Stadt am Niederrhein!", emoji: "🏙️" },
  HSK: { city: "Hochsauerlandkreis", message: "Schönes Sauerland!", emoji: "⛰️" },
  HST: { city: "Stralsund", message: "Hansestadt an der Ostsee!", emoji: "⚓" },
  HU: { city: "Hanau", message: "Brüder-Grimm-Stadt!", emoji: "📚" },
  HV: { city: "Havelberg", message: "Stadt an der Havel!", emoji: "🏙️" },
  HVL: { city: "Havelland", message: "Schönes Brandenburg!", emoji: "🏞️" },
  HWI: { city: "Wismar", message: "Hansestadt an der Ostsee!", emoji: "⚓" },
  HX: { city: "Höxter", message: "Stadt an der Weser!", emoji: "🏞️" },
  HY: { city: "Hoyerswerda", message: "Stadt in der Lausitz!", emoji: "🏙️" },
  HZ: { city: "Harz", message: "Schöner Harz!", emoji: "⛰️" },

  // I
  IGB: { city: "St. Ingbert", message: "Stadt im Saarland!", emoji: "🏙️" },
  IK: { city: "Ilm-Kreis", message: "Schönes Thüringen!", emoji: "🏞️" },
  IL: { city: "Ilmenau", message: "Universitätsstadt in Thüringen!", emoji: "🎓" },
  ILL: { city: "Illertissen", message: "Stadt in Schwaben!", emoji: "🏙️" },
  IN: { city: "Ingolstadt", message: "Autostadt an der Donau!", emoji: "🚗" },
  IZ: { city: "Itzehoe", message: "Stadt in Schleswig-Holstein!", emoji: "🏙️" },

  // J
  J: { city: "Jena", message: "Universitätsstadt in Thüringen!", emoji: "🎓" },
  JE: { city: "Jessen", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  JL: { city: "Jerichower Land", message: "Schönes Sachsen-Anhalt!", emoji: "🏞️" },
  JÜL: { city: "Jülich", message: "Stadt am Niederrhein!", emoji: "🏙️" },

  // K
  K: { city: "Köln", message: "Domstadt am Rhein!", emoji: "⛪" },
  KA: { city: "Karlsruhe", message: "Fächerstadt in Baden!", emoji: "🏛️" },
  KB: { city: "Waldeck-Frankenberg", message: "Schönes Nordhessen!", emoji: "🏞️" },
  KC: { city: "Kronach", message: "Stadt in Oberfranken!", emoji: "🏙️" },
  KE: { city: "Kempten", message: "Älteste Stadt Deutschlands!", emoji: "🏛️" },
  KEH: { city: "Kelheim", message: "Stadt an der Donau!", emoji: "🏞️" },
  KF: { city: "Kaufbeuren", message: "Stadt im Allgäu!", emoji: "🏙️" },
  KG: { city: "Bad Kissingen", message: "Bekannte Kurstadt!", emoji: "♨️" },
  KH: { city: "Bad Kreuznach", message: "Stadt an der Nahe!", emoji: "🏙️" },
  KI: { city: "Kiel", message: "Landeshauptstadt an der Ostsee!", emoji: "⚓" },
  KIB: { city: "Kirchheimbolanden", message: "Stadt in der Pfalz!", emoji: "🏙️" },
  KK: { city: "Kempen", message: "Stadt am Niederrhein!", emoji: "🏙️" },
  KL: { city: "Kaiserslautern", message: "Stadt in der Pfalz!", emoji: "🏙️" },
  KLE: { city: "Kleve", message: "Stadt am Niederrhein!", emoji: "🏙️" },
  KLZ: { city: "Klötze", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  KM: { city: "Kamenz", message: "Lessingstadt in Sachsen!", emoji: "📚" },
  KN: { city: "Konstanz", message: "Stadt am Bodensee!", emoji: "🏞️" },
  KO: { city: "Koblenz", message: "Stadt am Deutschen Eck!", emoji: "🏞️" },
  KÖN: { city: "Königstein", message: "Stadt im Taunus!", emoji: "⛰️" },
  KÖT: { city: "Köthen", message: "Bach-Stadt in Sachsen-Anhalt!", emoji: "🎵" },
  KÖZ: { city: "Kötzting", message: "Stadt im Bayerischen Wald!", emoji: "🌲" },
  KR: { city: "Krefeld", message: "Samt- und Seidenstadt!", emoji: "🧵" },
  KRU: { city: "Krumbach", message: "Stadt in Schwaben!", emoji: "🏙️" },
  KS: { city: "Kassel", message: "documenta-Stadt in Hessen!", emoji: "🎨" },
  KT: { city: "Kitzingen", message: "Weinstadt in Franken!", emoji: "🍇" },
  KU: { city: "Kulmbach", message: "Bierstadt in Oberfranken!", emoji: "🍺" },
  KÜN: { city: "Künzelsau", message: "Stadt in Baden-Württemberg!", emoji: "🏙️" },
  KUS: { city: "Kusel", message: "Stadt in der Pfalz!", emoji: "🏙️" },
  KW: { city: "Königs Wusterhausen", message: "Stadt in Brandenburg!", emoji: "🏙️" },
  KY: { city: "Kyritz", message: "Stadt in Brandenburg!", emoji: "🏙️" },
  KYF: { city: "Kyffhäuserkreis", message: "Schönes Thüringen!", emoji: "🏞️" },

  // L
  L: { city: "Leipzig", message: "Stadt der Musik und Kultur!", emoji: "🎵" },
  LA: { city: "Landshut", message: "Gotikstadt in Niederbayern!", emoji: "🏰" },
  LAU: { city: "Lauf", message: "Stadt in Mittelfranken!", emoji: "🏙️" },
  LB: { city: "Ludwigsburg", message: "Barockstadt in Württemberg!", emoji: "🏛️" },
  LBS: { city: "Lobenstein", message: "Stadt in Thüringen!", emoji: "🏙️" },
  LBZ: { city: "Lübz", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  LC: { city: "Luckau", message: "Stadt in Brandenburg!", emoji: "🏙️" },
  LD: { city: "Landau in der Pfalz", message: "Universitätsstadt in der Pfalz!", emoji: "🎓" },
  LDK: { city: "Lahn-Dill-Kreis", message: "Schönes Mittelhessen!", emoji: "🏞️" },

  LDS: { city: "Dahme-Spreewald", message: "Schönes Brandenburg!", emoji: "🏞️" },
  LEO: { city: "Leonberg", message: "Stadt in Baden-Württemberg!", emoji: "🏙️" },
  LER: { city: "Leer", message: "Stadt in Ostfriesland!", emoji: "🌊" },
  LEV: { city: "Leverkusen", message: "Stadt am Rhein!", emoji: "🏙️" },
  LG: { city: "Lüneburg", message: "Hansestadt in Niedersachsen!", emoji: "🏛️" },
  LH: { city: "Lüdinghausen", message: "Stadt im Münsterland!", emoji: "🏰" },
  LI: { city: "Lindau", message: "Stadt am Bodensee!", emoji: "🏞️" },
  LIB: { city: "Bad Liebenstein", message: "Kurstadt in Thüringen!", emoji: "♨️" },
  LIF: { city: "Lichtenfels", message: "Stadt in Oberfranken!", emoji: "🏙️" },
  LIP: { city: "Lippe", message: "Schönes Ostwestfalen!", emoji: "🏞️" },
  LL: { city: "Landsberg am Lech", message: "Stadt in Oberbayern!", emoji: "🏙️" },
  LM: { city: "Limburg-Weilburg", message: "Schönes Mittelhessen!", emoji: "🏞️" },
  LÖ: { city: "Lörrach", message: "Stadt im Dreiländereck!", emoji: "🏙️" },
  LÖB: { city: "Löbau", message: "Stadt in Sachsen!", emoji: "🏙️" },
  LOS: { city: "Oder-Spree", message: "Schönes Brandenburg!", emoji: "🏞️" },
  LP: { city: "Lippstadt", message: "Stadt in Westfalen!", emoji: "🏙️" },
  LR: { city: "Lahr", message: "Stadt im Schwarzwald!", emoji: "🌲" },
  LRO: { city: "Landkreis Rostock", message: "Schönes Mecklenburg!", emoji: "🏞️" },
  LSA: { city: "Sachsen-Anhalt", message: "Schönes Bundesland!", emoji: "🏛️" },
  LSN: { city: "Sachsen", message: "Freistaat mit Kultur!", emoji: "🏛️" },
  LSZ: { city: "Bad Langensalza", message: "Kurstadt in Thüringen!", emoji: "♨️" },
  LU: { city: "Ludwigshafen", message: "Stadt am Rhein!", emoji: "🏙️" },
  LÜN: { city: "Lünen", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  LUP: { city: "Ludwigslust-Parchim", message: "Schönes Mecklenburg!", emoji: "🏞️" },
  LWL: { city: "Ludwigslust", message: "Stadt in Mecklenburg!", emoji: "🏙️" },

  // M
  M: { city: "München", message: "Weltstadt mit Herz!", emoji: "🍺" },
  MA: { city: "Mannheim", message: "Quadratestadt am Rhein!", emoji: "🏙️" },
  MAB: { city: "Marienberg", message: "Stadt im Erzgebirge!", emoji: "⛰️" },
  MAI: { city: "Mainburg", message: "Stadt in Niederbayern!", emoji: "🏙️" },
  MAK: { city: "Marktredwitz", message: "Stadt in Oberfranken!", emoji: "🏙️" },
  MAL: { city: "Malchin", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  MB: { city: "Miesbach", message: "Stadt in Oberbayern!", emoji: "🏙️" },
  MC: { city: "Malchin", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  MD: { city: "Magdeburg", message: "Landeshauptstadt Sachsen-Anhalts!", emoji: "🏛️" },
  ME: { city: "Mettmann", message: "Stadt in Nordrhein-Westfalen!", emoji: "🏙️" },
  MEI: { city: "Meißen", message: "Porzellanstadt in Sachsen!", emoji: "🏺" },
  MEK: { city: "Mittelsachsen", message: "Schönes Sachsen!", emoji: "🏞️" },
  MEL: { city: "Melle", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  MER: { city: "Merseburg", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  MET: { city: "Mettmann", message: "Stadt in Nordrhein-Westfalen!", emoji: "🏙️" },
  MG: { city: "Mönchengladbach", message: "Stadt am Niederrhein!", emoji: "🏙️" },
  MGH: { city: "Bad Mergentheim", message: "Kurstadt in Baden-Württemberg!", emoji: "♨️" },
  MGN: { city: "Meiningen", message: "Theaterstadt in Thüringen!", emoji: "🎭" },
  MH: { city: "Mülheim an der Ruhr", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  MHL: { city: "Mühlhausen", message: "Stadt in Thüringen!", emoji: "🏙️" },
  MI: { city: "Minden-Lübbecke", message: "Schönes Ostwestfalen!", emoji: "🏞️" },
  MIL: { city: "Miltenberg", message: "Stadt in Unterfranken!", emoji: "🏙️" },
  MK: { city: "Märkischer Kreis", message: "Schönes Sauerland!", emoji: "⛰️" },
  ML: { city: "Mansfeld-Südharz", message: "Schönes Sachsen-Anhalt!", emoji: "🏞️" },
  MM: { city: "Memmingen", message: "Stadt in Schwaben!", emoji: "🏙️" },
  MN: { city: "Mindelheim", message: "Stadt in Schwaben!", emoji: "🏙️" },
  MO: { city: "Moers", message: "Stadt am Niederrhein!", emoji: "🏙️" },
  MOD: { city: "Marktoberdorf", message: "Stadt im Allgäu!", emoji: "🏙️" },
  MOL: { city: "Märkisch-Oderland", message: "Schönes Brandenburg!", emoji: "🏞️" },
  MON: { city: "Monschau", message: "Stadt in der Eifel!", emoji: "🏞️" },
  MOS: { city: "Mosbach", message: "Stadt in Baden!", emoji: "🏙️" },
  MQ: { city: "Merseburg-Querfurt", message: "Region in Sachsen-Anhalt!", emoji: "🏞️" },
  MR: { city: "Marburg-Biedenkopf", message: "Schönes Mittelhessen!", emoji: "🏞️" },
  MS: { city: "Münster", message: "Fahrradstadt in Westfalen!", emoji: "🚲" },
  MSE: { city: "Mecklenburgische Seenplatte", message: "Schöne Seenlandschaft!", emoji: "🏞️" },
  MSH: { city: "Mansfeld-Südharz", message: "Schönes Sachsen-Anhalt!", emoji: "🏞️" },
  MSP: { city: "Main-Spessart", message: "Schönes Unterfranken!", emoji: "🏞️" },
  MST: { city: "Mecklenburg-Strelitz", message: "Schönes Mecklenburg!", emoji: "🏞️" },
  MTK: { city: "Main-Taunus-Kreis", message: "Schönes Hessen!", emoji: "🏞️" },
  MTL: { city: "Mittweida", message: "Stadt in Sachsen!", emoji: "🏙️" },
  MÜ: { city: "Mühldorf am Inn", message: "Stadt in Oberbayern!", emoji: "🏙️" },
  MÜR: { city: "Müritz", message: "Schöne Seenlandschaft!", emoji: "🏞️" },
  MVL: { city: "Mecklenburg-Vorpommern", message: "Land der tausend Seen!", emoji: "🏞️" },
  MW: { city: "Mittweida", message: "Stadt in Sachsen!", emoji: "🏙️" },
  MY: { city: "Mayen", message: "Stadt in der Eifel!", emoji: "🏙️" },
  MYK: { city: "Mayen-Koblenz", message: "Schönes Rheinland-Pfalz!", emoji: "🏞️" },
  MZ: { city: "Mainz", message: "Landeshauptstadt von Rheinland-Pfalz!", emoji: "🏛️" },
  MZG: { city: "Merzig-Wadern", message: "Schönes Saarland!", emoji: "🏞️" },

  // N
  N: { city: "Nürnberg", message: "Stadt der Lebkuchen!", emoji: "🍪" },
  NAB: { city: "Nabburg", message: "Stadt in der Oberpfalz!", emoji: "🏙️" },
  NAI: { city: "Naila", message: "Stadt in Oberfranken!", emoji: "🏙️" },
  NAU: { city: "Nauen", message: "Stadt in Brandenburg!", emoji: "🏙️" },
  NB: { city: "Neubrandenburg", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  ND: { city: "Neuburg-Schrobenhausen", message: "Schönes Bayern!", emoji: "🏞️" },
  NDH: { city: "Nordhausen", message: "Stadt in Thüringen!", emoji: "🏙️" },
  NE: { city: "Neuss", message: "Stadt am Rhein!", emoji: "🏙️" },
  NEA: { city: "Neustadt an der Aisch", message: "Stadt in Mittelfranken!", emoji: "🏙️" },
  NEB: { city: "Nebra", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  NEC: { city: "Neustadt bei Coburg", message: "Stadt in Oberfranken!", emoji: "🏙️" },
  NES: { city: "Rhön-Grabfeld", message: "Schönes Unterfranken!", emoji: "🏞️" },
  NEW: { city: "Neustadt an der Waldnaab", message: "Stadt in der Oberpfalz!", emoji: "🏙️" },
  NF: { city: "Nordfriesland", message: "Schöne Nordseeküste!", emoji: "🌊" },
  NH: { city: "Neuhaus am Rennweg", message: "Stadt in Thüringen!", emoji: "🏙️" },
  NI: { city: "Nienburg", message: "Stadt an der Weser!", emoji: "🏞️" },
  NK: { city: "Neunkirchen", message: "Stadt im Saarland!", emoji: "🏙️" },
  NL: { city: "Niederlausitz", message: "Schönes Brandenburg!", emoji: "🏞️" },
  NM: { city: "Neumarkt in der Oberpfalz", message: "Stadt in der Oberpfalz!", emoji: "🏙️" },
  NMB: { city: "Naumburg", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  NMS: { city: "Neumünster", message: "Stadt in Schleswig-Holstein!", emoji: "🏙️" },
  NÖ: { city: "Nördlingen", message: "Stadt im Ries!", emoji: "🏙️" },
  NOH: { city: "Grafschaft Bentheim", message: "Schönes Niedersachsen!", emoji: "🏞️" },
  NOL: { city: "Niederschlesischer Oberlausitzkreis", message: "Schönes Sachsen!", emoji: "🏞️" },
  NOM: { city: "Northeim", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  NOR: { city: "Norden", message: "Stadt in Ostfriesland!", emoji: "🌊" },
  NP: { city: "Neuruppin", message: "Stadt in Brandenburg!", emoji: "🏙️" },
  NR: { city: "Neuwied", message: "Stadt am Rhein!", emoji: "🏞️" },
  NRW: { city: "Nordrhein-Westfalen", message: "Bevölkerungsreichstes Bundesland!", emoji: "🏛️" },
  NT: { city: "Nürtingen", message: "Stadt am Neckar!", emoji: "🏞️" },
  NU: { city: "Neu-Ulm", message: "Stadt an der Donau!", emoji: "🏞️" },
  NVP: { city: "Nordvorpommern", message: "Schöne Ostseeküste!", emoji: "🌊" },
  NW: { city: "Neustadt an der Weinstraße", message: "Stadt in der Pfalz!", emoji: "🍇" },
  NWM: { city: "Nordwestmecklenburg", message: "Schönes Mecklenburg!", emoji: "🏞️" },
  NY: { city: "Nidderau", message: "Stadt in Hessen!", emoji: "🏙️" },
  NZ: { city: "Neustrelitz", message: "Stadt in Mecklenburg!", emoji: "🏙️" },

  // O
  OA: { city: "Oberallgäu", message: "Traumhafte Alpenlandschaft!", emoji: "🏔️" },
  OAL: { city: "Ostallgäu", message: "Schönes Allgäu!", emoji: "🏞️" },
  OB: { city: "Oberhausen", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  OBB: { city: "Oberbayern", message: "Schönes Bayern!", emoji: "🏞️" },
  OBG: { city: "Osterburg", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  OC: { city: "Oschersleben", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  OCH: { city: "Ochsenfurt", message: "Stadt in Unterfranken!", emoji: "🏙️" },
  OD: { city: "Stormarn", message: "Schönes Schleswig-Holstein!", emoji: "🏞️" },
  OE: { city: "Olpe", message: "Stadt im Sauerland!", emoji: "⛰️" },
  OF: { city: "Offenbach", message: "Stadt am Main!", emoji: "🏙️" },
  OG: { city: "Offenburg", message: "Stadt in Baden!", emoji: "🏙️" },
  OH: { city: "Ostholstein", message: "Schöne Ostseeküste!", emoji: "🌊" },
  OHA: { city: "Osterode am Harz", message: "Stadt im Harz!", emoji: "⛰️" },
  OHV: { city: "Oberhavel", message: "Schönes Brandenburg!", emoji: "🏞️" },
  OHZ: { city: "Osterholz", message: "Schönes Niedersachsen!", emoji: "🏞️" },
  OK: { city: "Ohrekreis", message: "Region in Sachsen-Anhalt!", emoji: "🏞️" },
  OL: { city: "Oldenburg", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  OPR: { city: "Ostprignitz-Ruppin", message: "Schönes Brandenburg!", emoji: "🏞️" },
  OS: { city: "Osnabrück", message: "Stadt des Westfälischen Friedens!", emoji: "🕊️" },
  OSL: { city: "Oberspreewald-Lausitz", message: "Schönes Brandenburg!", emoji: "🏞️" },
  OVI: { city: "Oberviechtach", message: "Stadt in der Oberpfalz!", emoji: "🏙️" },
  OVL: { city: "Obervogtland", message: "Schönes Sachsen!", emoji: "🏞️" },
  OVP: { city: "Ostvorpommern", message: "Schöne Ostseeküste!", emoji: "🌊" },
  OZ: { city: "Oschatz", message: "Stadt in Sachsen!", emoji: "🏙️" },

  // P
  P: { city: "Potsdam", message: "Landeshauptstadt Brandenburgs!", emoji: "🏛️" },
  PA: { city: "Passau", message: "Dreiflüssestadt in Niederbayern!", emoji: "🏞️" },
  PAF: { city: "Pfaffenhofen an der Ilm", message: "Stadt in Oberbayern!", emoji: "🏙️" },
  PAN: { city: "Rottal-Inn", message: "Schönes Niederbayern!", emoji: "🏞️" },
  PAR: { city: "Parchim", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  PB: { city: "Paderborn", message: "Universitätsstadt in Westfalen!", emoji: "🎓" },
  PCH: { city: "Parchim", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  PE: { city: "Peine", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  PEG: { city: "Pegnitz", message: "Stadt in Oberfranken!", emoji: "🏙️" },
  PF: { city: "Pforzheim", message: "Goldstadt in Baden!", emoji: "💍" },
  PI: { city: "Pinneberg", message: "Stadt in Schleswig-Holstein!", emoji: "🏙️" },
  PIR: { city: "Pirna", message: "Tor zur Sächsischen Schweiz!", emoji: "⛰️" },
  PL: { city: "Plauen", message: "Spitzenstadt im Vogtland!", emoji: "🧵" },
  PLÖ: { city: "Plön", message: "Stadt in Schleswig-Holstein!", emoji: "🏙️" },
  PM: { city: "Potsdam-Mittelmark", message: "Schönes Brandenburg!", emoji: "🏞️" },
  PN: { city: "Possneck", message: "Stadt in Thüringen!", emoji: "🏙️" },
  PR: { city: "Prignitz", message: "Schönes Brandenburg!", emoji: "🏞️" },
  PRÜ: { city: "Prüm", message: "Stadt in der Eifel!", emoji: "🏙️" },
  PS: { city: "Pirmasens", message: "Stadt in der Pfalz!", emoji: "🏙️" },
  PW: { city: "Pasewalk", message: "Stadt in Vorpommern!", emoji: "🏙️" },
  PZ: { city: "Prenzlau", message: "Stadt in der Uckermark!", emoji: "🏙️" },

  // Q
  QFT: { city: "Querfurt", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },

  // R
  R: { city: "Regensburg", message: "UNESCO-Weltkulturerbe in Bayern!", emoji: "🏛️" },
  RA: { city: "Rastatt", message: "Stadt in Baden!", emoji: "🏙️" },
  RC: { city: "Reichenbach im Vogtland", message: "Stadt in Sachsen!", emoji: "🏙️" },
  RD: { city: "Rendsburg-Eckernförde", message: "Schönes Schleswig-Holstein!", emoji: "🏞️" },
  RE: { city: "Recklinghausen", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  REG: { city: "Regen", message: "Stadt im Bayerischen Wald!", emoji: "🌲" },
  REH: { city: "Rehau", message: "Stadt in Oberfranken!", emoji: "🏙️" },
  REI: { city: "Bad Reichenhall", message: "Kurstadt in Oberbayern!", emoji: "♨️" },
  RH: { city: "Roth", message: "Stadt in Mittelfranken!", emoji: "🏙️" },
  RI: { city: "Rinteln", message: "Stadt an der Weser!", emoji: "🏞️" },
  RID: { city: "Riedenburg", message: "Stadt in Niederbayern!", emoji: "🏙️" },
  RIE: { city: "Riesa", message: "Stadt in Sachsen!", emoji: "🏙️" },
  RL: { city: "Rochlitz", message: "Stadt in Sachsen!", emoji: "🏙️" },
  RM: { city: "Röbel/Müritz", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  RO: { city: "Rosenheim", message: "Stadt in Oberbayern!", emoji: "🏙️" },
  ROD: { city: "Roding", message: "Stadt in der Oberpfalz!", emoji: "🏙️" },
  ROF: { city: "Rotenburg an der Fulda", message: "Stadt in Hessen!", emoji: "🏙️" },
  ROK: { city: "Rockenhausen", message: "Stadt in der Pfalz!", emoji: "🏙️" },
  ROL: { city: "Rottenburg an der Laaber", message: "Stadt in Niederbayern!", emoji: "🏙️" },
  ROS: { city: "Rostock", message: "Hansestadt an der Ostsee!", emoji: "⚓" },
  ROT: { city: "Rottweil", message: "Älteste Stadt Baden-Württembergs!", emoji: "🏛️" },
  ROW: { city: "Rotenburg (Wümme)", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  RP: { city: "Rhein-Pfalz-Kreis", message: "Schönes Rheinland-Pfalz!", emoji: "🏞️" },
  RPL: { city: "Rheinland-Pfalz", message: "Land der Burgen und Weine!", emoji: "🏰" },
  RS: { city: "Remscheid", message: "Stadt im Bergischen Land!", emoji: "⛰️" },
  RSL: { city: "Rosslau", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  RT: { city: "Reutlingen", message: "Stadt in Baden-Württemberg!", emoji: "🏙️" },
  RU: { city: "Rudolstadt", message: "Stadt in Thüringen!", emoji: "🏙️" },
  RÜD: { city: "Rüdesheim", message: "Stadt am Rhein!", emoji: "🍇" },
  RÜG: { city: "Rügen", message: "Schöne Ostseeinsel!", emoji: "🏝️" },
  RV: { city: "Ravensburg", message: "Stadt in Oberschwaben!", emoji: "🏙️" },
  RW: { city: "Rottweil", message: "Älteste Stadt Baden-Württembergs!", emoji: "🏛️" },
  RZ: { city: "Herzogtum Lauenburg", message: "Schönes Schleswig-Holstein!", emoji: "🏞️" },

  // S
  S: { city: "Stuttgart", message: "Landeshauptstadt Baden-Württembergs!", emoji: "🏛️" },
  SAB: { city: "Saarburg", message: "Stadt an der Saar!", emoji: "🏞️" },
  SAD: { city: "Schwandorf", message: "Stadt in der Oberpfalz!", emoji: "🏙️" },
  SAL: { city: "Salzgitter", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  SAW: { city: "Salzwedel", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  SB: { city: "Saarbrücken", message: "Landeshauptstadt des Saarlandes!", emoji: "🏛️" },
  SBG: { city: "Strasburg", message: "Stadt in Vorpommern!", emoji: "🏙️" },
  SBK: { city: "Schönebeck", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  SC: { city: "Schwabach", message: "Stadt in Mittelfranken!", emoji: "🏙️" },
  SCZ: { city: "Schleiz", message: "Stadt in Thüringen!", emoji: "🏙️" },
  SDH: { city: "Sondershausen", message: "Stadt in Thüringen!", emoji: "🏙️" },
  SDL: { city: "Stendal", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  SDT: { city: "Schwedt", message: "Stadt in Brandenburg!", emoji: "🏙️" },
  SE: { city: "Segeberg", message: "Schönes Schleswig-Holstein!", emoji: "🏞️" },
  SEB: { city: "Sebnitz", message: "Stadt in Sachsen!", emoji: "🏙️" },
  SEE: { city: "Seelow", message: "Stadt in Brandenburg!", emoji: "🏙️" },
  SEF: { city: "Scheinfeld", message: "Stadt in Mittelfranken!", emoji: "🏙️" },
  SEL: { city: "Selb", message: "Porzellanstadt in Oberfranken!", emoji: "🏺" },
  SFA: { city: "Soltau-Fallingbostel", message: "Schöne Lüneburger Heide!", emoji: "🌾" },
  SFB: { city: "Senftenberg", message: "Stadt in Brandenburg!", emoji: "🏙️" },
  SFT: { city: "Staßfurt", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  SG: { city: "Solingen", message: "Klingenstadt im Bergischen Land!", emoji: "🔪" },
  SGH: { city: "Sangerhausen", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  SH: { city: "Schleswig-Holstein", message: "Land zwischen den Meeren!", emoji: "🌊" },
  SHA: { city: "Schwäbisch Hall", message: "Stadt in Baden-Württemberg!", emoji: "🏙️" },
  SHG: { city: "Schaumburg", message: "Schönes Niedersachsen!", emoji: "🏞️" },
  SHK: { city: "Saale-Holzland-Kreis", message: "Schönes Thüringen!", emoji: "🏞️" },
  SI: { city: "Siegen-Wittgenstein", message: "Schönes Siegerland!", emoji: "🏞️" },
  SIG: { city: "Sigmaringen", message: "Stadt in Baden-Württemberg!", emoji: "🏙️" },
  SIM: { city: "Rhein-Hunsrück-Kreis", message: "Schöner Hunsrück!", emoji: "🏞️" },
  SK: { city: "Saalkreis", message: "Region in Sachsen-Anhalt!", emoji: "🏞️" },
  SL: { city: "Schleswig-Flensburg", message: "Schönes Schleswig-Holstein!", emoji: "🏞️" },
  SLF: { city: "Saalfeld-Rudolstadt", message: "Schönes Thüringen!", emoji: "🏞️" },
  SLG: { city: "Mecklenburg-Strelitz", message: "Schönes Mecklenburg!", emoji: "🏞️" },
  SLK: { city: "Salzlandkreis", message: "Schönes Sachsen-Anhalt!", emoji: "🏞️" },
  SLN: { city: "Schmölln", message: "Stadt in Thüringen!", emoji: "🏙️" },
  SLS: { city: "Saarlouis", message: "Stadt im Saarland!", emoji: "🏙️" },
  SLÜ: { city: "Schlüchtern", message: "Stadt in Hessen!", emoji: "🏙️" },
  SLZ: { city: "Bad Salzungen", message: "Stadt in Thüringen!", emoji: "♨️" },
  SM: { city: "Schmalkalden-Meiningen", message: "Schönes Thüringen!", emoji: "🏞️" },
  SN: { city: "Schwerin", message: "Landeshauptstadt Mecklenburg-Vorpommerns!", emoji: "🏛️" },
  SNH: { city: "Sinsheim", message: "Stadt in Baden-Württemberg!", emoji: "🏙️" },
  SO: { city: "Soest", message: "Stadt in Westfalen!", emoji: "🏙️" },
  SOB: { city: "Schrobenhausen", message: "Stadt in Oberbayern!", emoji: "🏙️" },
  SOG: { city: "Schongau", message: "Stadt in Oberbayern!", emoji: "🏙️" },
  SOK: { city: "Saale-Orla-Kreis", message: "Schönes Thüringen!", emoji: "🏞️" },
  SOL: { city: "Soltau", message: "Stadt in der Lüneburger Heide!", emoji: "🌾" },
  SON: { city: "Sonneberg", message: "Stadt in Thüringen!", emoji: "🏙️" },
  SP: { city: "Speyer", message: "Domstadt am Rhein!", emoji: "⛪" },
  SPB: { city: "Spremberg", message: "Stadt in Brandenburg!", emoji: "🏙️" },
  SPN: { city: "Spree-Neiße", message: "Schönes Brandenburg!", emoji: "🏞️" },
  SR: { city: "Straubing", message: "Stadt in Niederbayern!", emoji: "🏙️" },
  SRB: { city: "Strausberg", message: "Stadt in Brandenburg!", emoji: "🏙️" },
  SRO: { city: "Stadtroda", message: "Stadt in Thüringen!", emoji: "🏙️" },
  ST: { city: "Steinfurt", message: "Schönes Münsterland!", emoji: "🏞️" },
  STA: { city: "Starnberg", message: "Stadt am See in Oberbayern!", emoji: "🏞️" },
  STB: { city: "Sternberg", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  STD: { city: "Stade", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  STE: { city: "Staffelstein", message: "Stadt in Oberfranken!", emoji: "🏙️" },
  STL: { city: "Stollberg", message: "Stadt in Sachsen!", emoji: "🏙️" },
  SU: { city: "Rhein-Sieg-Kreis", message: "Schönes Rheinland!", emoji: "🏞️" },
  SUL: { city: "Suhl", message: "Stadt in Thüringen!", emoji: "🏙️" },
  SW: { city: "Schweinfurt", message: "Stadt in Unterfranken!", emoji: "🏙️" },
  SWA: { city: "Bad Schwalbach", message: "Stadt im Taunus!", emoji: "⛰️" },
  SZ: { city: "Salzgitter", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  SZB: { city: "Schwarzenberg", message: "Stadt im Erzgebirge!", emoji: "⛰️" },

  // T
  TBB: { city: "Main-Tauber-Kreis", message: "Schönes Baden-Württemberg!", emoji: "🏞️" },
  TDO: { city: "Torgau-Oschatz", message: "Region in Sachsen!", emoji: "🏞️" },
  TE: { city: "Tecklenburg", message: "Stadt in Westfalen!", emoji: "🏙️" },
  TET: { city: "Teterow", message: "Stadt in Mecklenburg!", emoji: "🏙️" },
  TF: { city: "Teltow-Fläming", message: "Schönes Brandenburg!", emoji: "🏞️" },
  TG: { city: "Torgau", message: "Stadt in Sachsen!", emoji: "🏙️" },
  THL: { city: "Thüringen", message: "Grünes Herz Deutschlands!", emoji: "🏛️" },
  THW: { city: "Technisches Hilfswerk", message: "Immer zur Stelle!", emoji: "🛠️" },
  TIR: { city: "Tirschenreuth", message: "Stadt in der Oberpfalz!", emoji: "🏙️" },
  TO: { city: "Torgau", message: "Stadt in Sachsen!", emoji: "🏙️" },
  TÖL: { city: "Bad Tölz", message: "Stadt in Oberbayern!", emoji: "🏙️" },
  TP: { city: "Templin", message: "Stadt in Brandenburg!", emoji: "🏙️" },
  TR: { city: "Trier", message: "Älteste Stadt Deutschlands!", emoji: "🏛️" },
  TS: { city: "Traunstein", message: "Stadt in Oberbayern!", emoji: "🏙️" },
  TÜ: { city: "Tübingen", message: "Universitätsstadt am Neckar!", emoji: "🎓" },
  TUT: { city: "Tuttlingen", message: "Stadt in Baden-Württemberg!", emoji: "🏙️" },
  UE: { city: "Uelzen", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  UEM: { city: "Ueckermünde", message: "Stadt in Vorpommern!", emoji: "🏙️" },
  UFF: { city: "Uffenheim", message: "Stadt in Mittelfranken!", emoji: "🏙️" },
  UH: { city: "Unstrut-Hainich-Kreis", message: "Schönes Thüringen!", emoji: "🏞️" },
  UL: { city: "Ulm", message: "Stadt mit dem höchsten Kirchturm der Welt!", emoji: "⛪" },
  UM: { city: "Uckermark", message: "Schönes Brandenburg!", emoji: "🏞️" },
  UN: { city: "Unna", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  USI: { city: "Usingen", message: "Stadt im Taunus!", emoji: "⛰️" },

  // V
  V: { city: "Vogtlandkreis", message: "Schönes Sachsen!", emoji: "🏞️" },
  VAI: { city: "Vaihingen an der Enz", message: "Stadt in Baden-Württemberg!", emoji: "🏙️" },
  VB: { city: "Vogelsbergkreis", message: "Schönes Hessen!", emoji: "🏞️" },
  VEC: { city: "Vechta", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  VER: { city: "Verden", message: "Stadt an der Aller!", emoji: "🏞️" },
  VG: { city: "Vorpommern-Greifswald", message: "Schöne Ostseeküste!", emoji: "🌊" },
  VIB: { city: "Vilsbiburg", message: "Stadt in Niederbayern!", emoji: "🏙️" },
  VIE: { city: "Viersen", message: "Stadt am Niederrhein!", emoji: "🏙️" },
  VK: { city: "Völklingen", message: "Stadt im Saarland!", emoji: "🏙️" },
  VL: { city: "Villingen-Schwenningen", message: "Stadt im Schwarzwald!", emoji: "🌲" },
  VOH: { city: "Vohenstrauß", message: "Stadt in der Oberpfalz!", emoji: "🏙️" },
  VR: { city: "Vorpommern-Rügen", message: "Schöne Ostseeküste!", emoji: "🌊" },
  VS: { city: "Villingen-Schwenningen", message: "Stadt im Schwarzwald!", emoji: "🌲" },
  VT: { city: "Verden", message: "Stadt an der Aller!", emoji: "🏞️" },

  // W
  W: { city: "Wuppertal", message: "Stadt der Schwebebahn!", emoji: "🚟" },
  WA: { city: "Waldeck-Frankenberg", message: "Schönes Nordhessen!", emoji: "🏞️" },
  WAF: { city: "Warendorf", message: "Stadt im Münsterland!", emoji: "🏙️" },
  WAK: { city: "Wartburgkreis", message: "Schönes Thüringen!", emoji: "🏞️" },
  WAN: { city: "Wanne-Eickel", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  WAT: { city: "Wattenscheid", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  WB: { city: "Wittenberg", message: "Lutherstadt in Sachsen-Anhalt!", emoji: "⛪" },
  WBS: { city: "Worbis", message: "Stadt in Thüringen!", emoji: "🏙️" },
  WDA: { city: "Werdau", message: "Stadt in Sachsen!", emoji: "🏙️" },
  WE: { city: "Weimar", message: "Kulturstadt in Thüringen!", emoji: "🎭" },
  WEL: { city: "Weilheim-Schongau", message: "Schönes Oberbayern!", emoji: "🏞️" },
  WEN: { city: "Weiden in der Oberpfalz", message: "Stadt in der Oberpfalz!", emoji: "🏙️" },
  WER: { city: "Wertingen", message: "Stadt in Schwaben!", emoji: "🏙️" },
  WES: { city: "Wesel", message: "Stadt am Niederrhein!", emoji: "🏙️" },
  WF: { city: "Wolfenbüttel", message: "Stadt in Niedersachsen!", emoji: "🏙️" },
  WHV: { city: "Wilhelmshaven", message: "Stadt an der Nordsee!", emoji: "⚓" },
  WI: { city: "Wiesbaden", message: "Landeshauptstadt Hessens!", emoji: "🏛️" },
  WIL: { city: "Bernkastel-Wittlich", message: "Schöne Moselregion!", emoji: "🍇" },
  WIS: { city: "Wismar", message: "Hansestadt an der Ostsee!", emoji: "⚓" },
  WIT: { city: "Witten", message: "Stadt im Ruhrgebiet!", emoji: "⚒️" },
  WK: { city: "Wiesbaden", message: "Landeshauptstadt Hessens!", emoji: "🏛️" },
  WL: { city: "Harburg", message: "Schönes Niedersachsen!", emoji: "🏞️" },
  WLG: { city: "Wolgast", message: "Stadt in Vorpommern!", emoji: "🏙️" },
  WM: { city: "Weilheim-Schongau", message: "Schönes Oberbayern!", emoji: "🏞️" },
  WMS: { city: "Worms", message: "Stadt am Rhein!", emoji: "🏙️" },
  WN: { city: "Waiblingen", message: "Stadt in Baden-Württemberg!", emoji: "🏙️" },
  WND: { city: "St. Wendel", message: "Stadt im Saarland!", emoji: "🏙️" },
  WO: { city: "Worms", message: "Stadt am Rhein!", emoji: "🏙️" },
  WOB: { city: "Wolfsburg", message: "Autostadt in Niedersachsen!", emoji: "🚗" },
  WOH: { city: "Wolfhagen", message: "Stadt in Nordhessen!", emoji: "🏙️" },
  WOL: { city: "Wolfratshausen", message: "Stadt in Oberbayern!", emoji: "🏙️" },
  WOR: { city: "Wolfratshausen", message: "Stadt in Oberbayern!", emoji: "🏙️" },
  WOS: { city: "Wolfstein", message: "Stadt in der Pfalz!", emoji: "🏙️" },
  WR: { city: "Wernigerode", message: "Bunte Stadt am Harz!", emoji: "⛰️" },
  WRN: { city: "Waren", message: "Stadt an der Müritz!", emoji: "🏞️" },
  WS: { city: "Wasserburg", message: "Stadt am Inn!", emoji: "🏞️" },
  WSF: { city: "Weißenfels", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  WST: { city: "Ammerland", message: "Schönes Niedersachsen!", emoji: "🏞️" },
  WSW: { city: "Weißwasser", message: "Stadt in Sachsen!", emoji: "🏙️" },
  WT: { city: "Waldshut", message: "Stadt in Baden!", emoji: "🏙️" },
  WTL: { city: "Wittlich", message: "Stadt in Rheinland-Pfalz!", emoji: "🏙️" },
  WTM: { city: "Wittmund", message: "Stadt in Ostfriesland!", emoji: "🌊" },
  WÜ: { city: "Würzburg", message: "Universitätsstadt in Franken!", emoji: "🎓" },
  WUG: { city: "Weißenburg-Gunzenhausen", message: "Schönes Mittelfranken!", emoji: "🏞️" },
  WUN: { city: "Wunsiedel", message: "Stadt in Oberfranken!", emoji: "🏙️" },
  WUR: { city: "Wurzen", message: "Stadt in Sachsen!", emoji: "🏙️" },
  WW: { city: "Westerwaldkreis", message: "Schöner Westerwald!", emoji: "🏞️" },
  WZ: { city: "Wetzlar", message: "Stadt in Mittelhessen!", emoji: "🏙️" },
  WZL: { city: "Wanzleben", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },

  // X
  X: { city: "Bundeswehr", message: "Für die Verteidigung!", emoji: "🪖" },

  // Y
  Y: { city: "Bundeswehr", message: "Für die Verteidigung!", emoji: "🪖" },

  // Z
  Z: { city: "Zwickau", message: "Stadt in Sachsen!", emoji: "🏙️" },
  ZE: { city: "Zerbst", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
  ZEL: { city: "Zell", message: "Stadt in Rheinland-Pfalz!", emoji: "🏙️" },
  ZI: { city: "Zittau", message: "Stadt in Sachsen!", emoji: "🏙️" },
  ZP: { city: "Zschopau", message: "Stadt in Sachsen!", emoji: "🏙️" },
  ZR: { city: "Zeulenroda", message: "Stadt in Thüringen!", emoji: "🏙️" },
  ZW: { city: "Zweibrücken", message: "Stadt in der Pfalz!", emoji: "🏙️" },
  ZZ: { city: "Zeitz", message: "Stadt in Sachsen-Anhalt!", emoji: "🏙️" },
}

/**
 * Gibt Informationen zu einer Stadt basierend auf dem Kennzeichenpräfix zurück
 * @param prefix Das Kennzeichenpräfix (z.B. "HH" für Hamburg)
 * @returns Informationen zur Stadt oder einen Standardwert, wenn die Stadt nicht gefunden wurde
 */
export const getCityInfo = (prefix: string) => {
  const cityInfo = licensePlatePrefixes[prefix.toUpperCase()]

  if (cityInfo) {
    return cityInfo
  }

  return {
    city: "Unbekannt",
    message: "Kennzeichen nicht erkannt",
    emoji: "❓",
  }
}

/**
 * Validiert ein deutsches Kennzeichen.
 * @param licensePlate Das zu validierende Kennzeichen (z.B. "HH-OZ-1997")
 * @returns true, wenn das Kennzeichen gültig ist, false sonst
 */
export const validateLicensePlate = (licensePlate: string): boolean => {
  if (!licensePlate) {
    return false
  }

  const parts = licensePlate.split("-")
  if (parts.length !== 3) {
    return false
  }

  const [part1, part2, part3] = parts

  // Erste Gruppe: 1-3 Buchstaben
  const isValidPart1 = /^[A-Z]{1,3}$/.test(part1)
  // Zweite Gruppe: 1-2 Buchstaben
  const isValidPart2 = /^[A-Z]{1,2}$/.test(part2)
  // Dritte Gruppe: 1-4 Ziffern
  const isValidPart3 = /^[0-9]{1,4}$/.test(part3)

  return isValidPart1 && isValidPart2 && isValidPart3
}
